### ISSUE TITLE
Algorithm issues

### ISSUE THREAD

**Issue by jmskurtz** [mostaphaRoudsari/EmergeSettlement#11]
https://docs.google.com/spreadsheets/d/1Rdb9R5--uQLwx0NqsR8qKNMnNwHsenGS8H0kGxGknjI/edit?usp=sharing

Here is the link the spreadsheet for documenting the equations. I haven't finished the Support areas, but the production areas should all be there. Questions are as follows:
- None of the sliders in yellow are included in Mostapha's model... should they be?
- How do we determine the J/acre of wind?
- Do we need to determine the production area for: Goods purchased, water, wastewater? I believe we said today the answer is no, but just want to confirm.

**Comment by mostaphaRoudsari** [comment]
1. I will add the sliders in Yellow.
2. I don't know. I leave this to @Butcherluke and Bill.
3. I agree that we should just keep it as simple as possible for now so we can create a prototype that works. We can add remove to formulas later. We still have so much work left.

I checked the file and there are still a couple of items that production area is not available. Does it mean that we do not need them? I think I will convert all the formulas to code together once ready so we can cross check the results otherwise it will be really hard to go back and forth and update the code based on latest version of spreadsheet. Let me know when you feel confident about the equations.

Also can you review this issue (#4) and let me know about the changes. I can see that they are already bundled in spreadsheet but looks like there are some items that are not under any of the categories that I need.

**Comment by jmskurtz** [comment]
Bill,
1. can you confirm if the sliders in yellow should be added. I know for sure food production/fuel production should but not sure of the others
2. how does moving the wind to the water change our land use area for needed for wind? we hadn't really given it actual area before but wondering if we should now.
3. can you review the equations I have listed and confirm they all make sense. 

Mostapha - the only ones that are 'missing' are ones we don't have but don't think we need. once Bill responds to the above, then the production equations should be done. Next I'll confirm the support area equations.

**Comment by brahamw** [comment]
Jill,
on 1. I think all the sliders you listed should be included except the depreciation of buildings and fuel production intensity. I agree the production of fuels should all be linked, so they don't exceed 100%, probably with 100% fossil fuels as starting point...
the production efficiency of energy doesn't affect the support area, which is the big area, so can be left out of this one.
things like goods, water, wastewater have either negligible areas or a non-exclusive.
I can look at J/acre of wind tomorrow, but thought you had that built in, and by including it in the water, we make it largely non-exclusive to other land uses...
bill

**Comment by brahamw** [comment]
Jill and Mostapha,
I went through the list of sliders that Jill prepared, edited, and proposed a final list and naming, with a few questions outstanding. Please review.
still working on the wind...

**Comment by jmskurtz** [comment]
okay sounds good. Will be working on this tonight and finalize all the
other equations.

On Wed, Mar 25, 2015 at 9:21 AM, brahamw <notifications@github.com> wrote:

> Jill and Mostapha,
> I went through the list of sliders that Jill prepared, edited, and
> proposed a final list and naming, with a few questions outstanding. Please
> review.
> still working on the wind...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mostaphaRoudsari/SettlementEmerge/issues/11#issuecomment-86020665>
> .
>



-- 
*J I L L  M.  S O R N S O N  K U R T Z*
design.jillm.com + rebuildsudan.org + rebuildconsult.com

**Comment by jmskurtz** [comment]
reviewed and discussed with mostapha to make sure things are in a form that
works for him.

responded to your notes by addressing them or leaving them in yellow.

made significant updates and just need to determine
1. how to include building size into the equations
2. emergy of the built environment.
3. Also, need to determine the algorithm for the 'renewable' land area and use that to finalize equations for the support area.

**Comment by jmskurtz** [comment]
Also, need to determine the algorithm for the 'renewable' land area and use
that to finalize equations for the support area.

On Thu, Mar 26, 2015 at 1:22 AM, Jill Sornson Kurtz <jmskurtz@gmail.com>
wrote:

> reviewed and discussed with mostapha to make sure things are in a form
> that works for him.
>
> responded to your notes by addressing them or leaving them in yellow.
>
> made significant updates and just need to determine
> 1. how to include building size into the equations
> 2. emergy of the built environment.
>
> On Wed, Mar 25, 2015 at 9:31 AM, Jill Sornson Kurtz <jmskurtz@gmail.com>
> wrote:
>
>> okay sounds good. Will be working on this tonight and finalize all the
>> other equations.
>>
>> On Wed, Mar 25, 2015 at 9:21 AM, brahamw <notifications@github.com>
>> wrote:
>>
>>> Jill and Mostapha,
>>> I went through the list of sliders that Jill prepared, edited, and
>>> proposed a final list and naming, with a few questions outstanding. Please
>>> review.
>>> still working on the wind...
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/mostaphaRoudsari/SettlementEmerge/issues/11#issuecomment-86020665>
>>> .
>>>
>>
>>
>>
>> --
>> *J I L L  M.  S O R N S O N  K U R T Z*
>> design.jillm.com + rebuildsudan.org + rebuildconsult.com
>>
>
>
>
> --
> *J I L L  M.  S O R N S O N  K U R T Z*
> design.jillm.com + rebuildsudan.org + rebuildconsult.com
>



-- 
*J I L L  M.  S O R N S O N  K U R T Z*
design.jillm.com + rebuildsudan.org + rebuildconsult.com

**Comment by brahamw** [comment]
found some good wind numbers J/acre, in wind spreadsheet, and will work on unifying them later.
will address the building size - efficiency in equations
what do you mean renewable land areas? is that the average renewable per acre?

**Comment by jmskurtz** [comment]
yeah, meant the average renewable per acre

On Thu, Mar 26, 2015 at 9:57 AM, brahamw notifications@github.com wrote:

> found some good wind numbers J/acre, in wind spreadsheet, and will work on
> unifying them later.
> will address the building size - efficiency in equations
> what do you mean renewable land areas? is that the average renewable per
> acre?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mostaphaRoudsari/SettlementEmerge/issues/11#issuecomment-86523567
> .

## 

_J I L L  M.  S O R N S O N  K U R T Z_
design.jillm.com + rebuildsudan.org + rebuildconsult.com

**Comment by brahamw** [comment]
I got two different numbers, depending on the approach, so will dig into that later.

**Comment by brahamw** [comment]
Finally tracked down the wind calculations, which are summarized in the revised wind sheet. basically our current calculations are for the energy and emergy content of the wind itself. 
A conservative estimate of the wind energy available on the water is 3 W/m2 or 3.83E+11 J/acre. It is slightly lower over land, of course. and the emergy intensity for the electricity from wind is 1.83E+04   sej/J (or 1.73E+12 sej/m2 yr for the wind over water). This all from Dolan, 2008, and the W/m2 estimate from MacKay

**Comment by brahamw** [comment]
Still haven't been able to work all the way through the difference between the average renewable per acre, which ranges from 8.09 E+14 sej/acre to 13.8 e14 sej/acre, so I suggest we use the lower number, which is more conservative.

**Comment by mostaphaRoudsari** [comment]
@brahamw  and @jmskurtz, should we close this?

**Comment by jmskurtz** [comment]
we're now down to needing 82 chatauquas. i've reviewed it a couple times and think something might be wrong with the intensity of renewables... @brahamw  can you review my assumptions (intensities) and algorithm for the renewables see if you can find an issue. If you think we should break out the renewables (sun, wind rain) instead of doing an average, I can do that too.

**Comment by Butcherluke** [comment]
We don't need to 'solve' this for the paper submission do we? A screenshot of the website in its most complete form would do? It can go 'live' with the conference itself.

**Comment by jmskurtz** [comment]
i thought we were going to include a table of the solved and baseline cases (table 1 in outline).

**Comment by Butcherluke** [comment]
I see merit in not solving it and solving it too. By solving it there is the potential to polarise opinion as the Vegan Singapore option did. You also need to justify the decisions about why that solution is the one you show over another solution (Assuming there is more than one!). For completeness it does feel right to show a completed solution but couldn't this come with the conference itself? And the paper proceedings just set the scene? The tool is still a work in progress in some ways (if you include the wish list items) and has come on so far since last summer (there are more points that can be calibrated for one) that I wouldn't want to put forward a solution when we know there are potential refinements that could follow.

**Comment by mostaphaRoudsari** [comment]
@jmskurtz I still get 133.34 from GoogleSpreadSheet.

**Comment by mostaphaRoudsari** [comment]
I agree that we don't to have a final solution but we should make sure that the numbers are correct for the current base scenario. I think we are not there yet. Hopefully @brahamw can check the numbers tomorrow.

**Comment by jmskurtz** [comment]
yeah, i guess one of the sliders had been moved to give me a lower number.
yes, even if we don't show the "final" results, we need to know the
baseline results are correct and 133 chatauquas is not right.

Bill, feel free to call me on my cell phone today if you want to discuss
after/when you review it. 510.928.0977

On Mon, Mar 30, 2015 at 12:34 AM, Mostapha Sadeghipour Roudsari <
notifications@github.com> wrote:

> I agree that we don't to have a final solution but we should make sure
> that the numbers are correct for the current base scenario. I think we are
> not there yet. Hopefully @brahamw https://github.com/brahamw can check
> the numbers tomorrow.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mostaphaRoudsari/SettlementEmerge/issues/11#issuecomment-87538672
> .

## 

_J I L L  M.  S O R N S O N   K U R T Z_
consultant http://revisionarch.com/  |  faculty
http://www.philau.edu/architectureandthebuiltenvironment/  |  fellow
http://www.design.upenn.edu/architecture/graduate/research/penn-tsinghua-tc-chan-center
  |  supporter http://www.rebuildsouthsudan.org/
