### ISSUE TITLE
Scenarios

### ISSUE THREAD

**Issue by Butcherluke** [mostaphaRoudsari/EmergeSettlement#12]
Initial thoughts on scenarios of how to distribute the population in the different models.
1. Baseline Distribution
   Each settlement point 'as is' with all population increases proportionate to that settlements ranking in the county, i.e. If 1000 people are added to the county then Jamestown sees the largest population growth. Doesn't account for 'urban centres' pulling population away from rural areas I know but does help with the original 'dilemma' of planning for a growing county, not a shrinking one.
2. Even Distribution
   All settlements have an equal share of the total population. Maybe not that realistic given the amount of population that Jamestown would loose but would speak to precedent for distributed cities (Broadacre comes to mind). Another potential problem is that there are a large number of settlement points clustered around Jamestown that would all be fluting over the same land (although the model could tell us if that in itself is sustainable).
3. Two Centres
   Takes the population and shares it evenly across two settlement points, Jamestown and Dunkirk would be good candidates. Accounts for existing infrastructure and it isn't unreasonable that these two places could each become denser. It would be interesting if the model could (in a future iteration) tell us the optimum two settlement points that population could be shared between (based on existing land allocation).
4. One Centre
   All population in a single point, probably Jamestown. As with the above option I wonder if there is an optimum settlement point in the county that may not be Jamestown (especially if you see the lake as a natural barrier to accessing some land types).

Future mode scenarios....(ignoring settlement points)
5. Complete distribution or the small homestead model (a patchwork quilt of land allocation based on what people need/use)
6. A new settlement in the optimum location

**Comment by mostaphaRoudsari** [comment]
We can't do scenarios 5 and 6 with the current model. For number 4 we can try a couple of different locations. Let's say both Jamestown and Dunkirk? 4-1 and 4-2?

**Comment by brahamw** [comment]
I like the four scenarios and agree that 4 could be done twice with Jamestown and Dunkirk, will be interesting spatially because of their relation to water

**Comment by Butcherluke** [comment]
Scenario 5 and 6 were 'wish lists' thinking about the next iteration.

@mostaphaRoudsari will the Scenarios appear as options (buttons?) that users activate? With a Scenario 4 split into A Jamestown and B Dunkirk there would be 5 scenarios?

**Comment by brahamw** [comment]
The scenarios pull down menu looks good, but think they need a one or two word explanation, Luke's names seem right

**Comment by mostaphaRoudsari** [comment]
@Butcherluke I have the drop down as a place holder there. I just put one scenario for 4 but we can add it back if needed. let me know when you have the numbers ready.

@brahamw Thanks. I will add the names that you have here instead of scenario1, 2, etc

**Comment by mostaphaRoudsari** [comment]
@Butcherluke  and @brahamw I updated the drop down, and copied part of the text for description of each case. It should show up if you hover your mouse on top of the option in drop down. Please review and let me know your comments.

**Comment by Butcherluke** [comment]
Did you want exact values for the population in each scenario? If it is formula based then these would be it:
1. Population for all 17 settlements equal to current populations (no change, default position)
2. Population at each settlement point = total population divided by number of settlements (17)
3. Population only assigned to Jamestown and Dunkirk. Population at Jamestown and Dunkirk = total population divided by 2. All other settlement points set to 0.
   4-1. Total population in a single settlement point, Jamestown. All other settlement points set to 0.
   4-2. Total population in a single settlement point, Dunkirk. All other settlement points set to 0.

**Comment by mostaphaRoudsari** [comment]
This is the values that I needed for this. I have 24 settlements here so I divide the number by 24. Please check the page for a working version of dropdown:

``` javascript
        var populationSc = [{Panama:4572, "Cherry Creek":5211, Ripley:2452, Brocton:5579,
                            Westfield:4896, Sherman:4813, Sinclairville: 4674, Fredonia: 11702, Cassadaga: 4527,
                            "Chautauqua Institution": 3618, Frewsburg: 5999, Busti: 4122, Kennedy: 4558, "Sunset Bay": 637,
                            Forestville: 4790, Dunkirk: 12836, "Silver Creek": 2035, Falconer: 2619, Celoron: 1686,
                            "Bemus Point": 4457, Mayville: 917, Lakewood: 3229, "Jamestown West": 1834, Jamestown: 31146},
                            {Panama:5538, "Cherry Creek":5538, Ripley:5538, Brocton:5538,
                            Westfield:5538, Sherman:5538, Sinclairville: 5538, Fredonia: 5538, Cassadaga: 5538,
                            "Chautauqua Institution": 5538, Frewsburg: 5538, Busti: 5538, Kennedy: 5538, "Sunset Bay": 5538,
                            Forestville: 5538, Dunkirk: 5538, "Silver Creek": 5538, Falconer: 5538, Celoron: 5538,
                            "Bemus Point": 5538, Mayville: 5538, Lakewood: 5538, "Jamestown West": 5538, Jamestown: 5538},
                            {Panama:0, "Cherry Creek":0, Ripley:0, Brocton:0,
                            Westfield:0, Sherman:0, Sinclairville: 0, Fredonia: 0, Cassadaga: 0,
                            "Chautauqua Institution": 0, Frewsburg: 0, Busti: 0, Kennedy: 0, "Sunset Bay": 0,
                            Forestville: 0, Dunkirk: 66454, "Silver Creek": 0, Falconer: 0, Celoron: 0,
                            "Bemus Point": 0, Mayville: 0, Lakewood: 0, "Jamestown West": 0, Jamestown: 66454},
                            {Panama:0, "Cherry Creek":0, Ripley:0, Brocton:0,
                            Westfield:0, Sherman:0, Sinclairville: 0, Fredonia: 0, Cassadaga: 0,
                            "Chautauqua Institution": 0, Frewsburg: 0, Busti: 0, Kennedy: 0, "Sunset Bay": 0,
                            Forestville: 0, Dunkirk: 0, "Silver Creek": 0, Falconer: 0, Celoron: 0,
                            "Bemus Point": 0, Mayville: 0, Lakewood: 0, "Jamestown West": 0, Jamestown: 132909}]
```
