### ISSUE TITLE
Report Land area for each scenario

### ISSUE THREAD

**Issue by mostaphaRoudsari** [mostaphaRoudsari/EmergeSettlement#21]
I really want this to be interactive but I need to keep it as simple as possible to finish it today. I will try two horizontal bar graphs colors for each land use.

**Comment by brahamw** [comment]
to make the game clear, I think we would need one bar that is the actual area of the county, and another which is the sum of the primary and support land. If that total is equal to or less than the actual county, the it should say that you have "won" the game!

**Comment by mostaphaRoudsari** [comment]
@brahamw please check the page. I added the bar chart and broken down the values for each land use.

**Comment by brahamw** [comment]
Mostapha,
The bar chart looks great, but is it actually reporting the total, or just the primary land area? It should be showing primary plus support land area.

For the titles, I would suggest “County Land Area” for the first one,
And “Area of your Scenario” for the second one.

And now I will show it to the students, but not let them actually play it…

Bill

Dr. William W. Braham, FAIA  | Director
Master of Environmental Building Design                 www.mebd-penndesign.infohttp://www.mebd-penndesign.info/
TC Chan Center                                                        www.design.upenn.edu/tcchancenterhttp://www.design.upenn.edu/tcchancenter

**Comment by Butcherluke** [comment]
There is a spelling mistake under Desired.

**Comment by mostaphaRoudsari** [comment]
Bill, as for the last night the values for default were 1.3*baseline since it doesn't really match the numbers from the googleSpreadSheet. If you click on Calculate Land Area it will load the real values which is pretty huge. I assume I'm missing some zeros in my calculation for County'd land area. Can you direct me to a table that I can double check my numbers?

Thanks you both. I fixed the titles (on my system for now and will push it soon)

**Comment by mostaphaRoudsari** [comment]
Now the values match with GoogleSpreadsheet and based on that we need 133.25 times more land for the base scenario!!!
