### ISSUE TITLE
Pixels on the map?

### ISSUE THREAD

**Issue by Butcherluke** [mostaphaRoudsari/EmergeSettlement#26]
How many pixels are there on the map?

**Comment by mostaphaRoudsari** [comment]
I exported the map in two different resolutions. The current one which is the low resolution version has 6021. Why?

**Comment by Butcherluke** [comment]
I am adding a note in the paper for my section about how many acres a single pixel represents.

**Comment by mostaphaRoudsari** [comment]
based on total area of  (960115) it is > 159.46105298123234
