### ISSUE TITLE
Rephrase this please

### ISSUE THREAD

**Issue by mostaphaRoudsari** [mostaphaRoudsari/EmergeSettlement#27]
I added some notes for users which probably needs to be rephrased. I'm copying it here for your review:

This:
Currently we need 133.25 Chautauquas to support the current life style of the people. We need you to find a better solution that can support the population on the resources of the county.

and this:
You need 133.25 Chautauquas to support this scenario. Oops!!!

**Comment by Butcherluke** [comment]
We need 133.25 Chautauqua Countys to support the current life style of the population. We need your help in identifying a better solution that only uses the resources of the county.

Oops! You need 133.25 Chautauquas to support this lifestyle. Maybe you should try something different?

How about those?

**Comment by mostaphaRoudsari** [comment]
Thanks!
