### ISSUE TITLE
Add sliders

### ISSUE THREAD

**Issue by mostaphaRoudsari** [mostaphaRoudsari/EmergeSettlement#3]
Here is the list of parameters
## Developed
1. Population > 0 to 200,000 It is not connected to anywhere so I'm not sure how it works
2. Density > 0.1 to 2.0 | current : 1.0
## Energy
1. Energy Demand >  0.1 to 2.0 | current : 1.0
2. Energy Mix - PVs > 0.1 to 1.0 | current : 0.0
3. Energy Mix - BioMass (Forest) > 0.1 to 1.0 | current : 0.1
4. EnergyMix - Wind > 0.1 to 1.0 | current : 0.0
5. EnergyMix - Wave > 0.1 to 1.0 | current : 0.0
## Food
1. Food Demand >  0.1 to 2.0 | current : 1.0
2. Diet - Grains > 0.00 to 1.00 | current : 0.46
3. Diet - Vegetables > 0.00 to 1.00 | current : 0.12
4. Diet - Fruit > 0.00 to 1.00 | current : 0.09
5. Diet - Dairy > 0.00 to 1.00 | current : 0.05
6. Diet - Meat > 0.00 to 1.00 | current : 0.23
7. Diet - Fish > 0.00 to 1.00 | current : 0.05
## Transport
1. Average miles Driven >  0.1 to 2.0 | current : 1.0
2. ?
3. ?
4. Vehicle Efficiency >  0.1 to 2.0 | current : 1.0
5. Gasoline Mix - Bio Fuels (Agriculture)> 0.00 to 1.00 | current : 0.10

Default values should eventually come from google spreadsheet but for now I set them up inside html file.

Here is a good example > http://bl.ocks.org/d3noob/10632804

Pretty versions:
http://codepen.io/thebabydino/pen/myqzEp
http://codepen.io/thebabydino/pen/YPOPxr

**Comment by jmskurtz** [comment]
here is the google spreadsheet inputs: https://docs.google.com/spreadsheets/d/1ZAfqv2V8dOPtQbBOFiIc3IVQLt8KKblRiZ8gWa_7JcY/edit?usp=sharing

**Comment by jmskurtz** [comment]
I think the sliders are best (over the circles) because the circles indicate areas. http://codepen.io/thebabydino/pen/myqzEp

**Comment by mostaphaRoudsari** [comment]
@jmskurtz thanks for the google file. circles right now just indicates locations, also currently values are set globally and not for every single city so it will be one set of sliders for all.

**Comment by mostaphaRoudsari** [comment]
Good for now. Next step is to connect this values to functions to calculate need for each settlement. See #4. 
![image](https://cloud.githubusercontent.com/assets/2915573/6650587/f83d7b94-c9f0-11e4-97e8-d5d0079a1ccb.png)
