### ISSUE TITLE
Change colors for change of landuse

### ISSUE THREAD

**Issue by mostaphaRoudsari** [mostaphaRoudsari/EmergeSettlement#34]

**Comment by mostaphaRoudsari** [comment]
I mistakenly closed this one instead of #36.

**Comment by mostaphaRoudsari** [comment]
@Butcherluke I can check the old files but if you can tell me it will be much easier. What was the logic again here for the second round? For both "Agriculture" or "Forest" we can use "Natural" land?

**Comment by Butcherluke** [comment]
Yes that is right. Any allocated land (except Wetlands or Water) was up for grabs in the original model. It goes back to our discussions about the game being human centric and not valuing 'natural' land.

**Comment by mostaphaRoudsari** [comment]
Thanks... so does it also means that 'natural' can be taken and changed to a 'developed' land?

**Comment by Butcherluke** [comment]
I think so yes. Or rather I'm happy for that to be the case. There are arguments for and against but for the purpose of the this exercise I think it makes sense.

**Comment by Butcherluke** [comment]
@mostaphaRoudsari it looks like the mapping is working, am I right? I like the way you can click on a settlement point and see its boundary and where cells are being taken from. Is this map just for production land now?

**Comment by mostaphaRoudsari** [comment]
@Butcherluke now it works! and yes it is only the production land - no support and that's what we have all the support in grey in bar chart.
