### ISSUE TITLE
Calculate need for each land use

### ISSUE THREAD

**Issue by mostaphaRoudsari** [mostaphaRoudsari/EmergeSettlement#4]
Here are the formulas that I tried to put back together from GH definition. Inputs are referenced from sliders (see #3)

Developed Area needed = population \* (developedArea/person (= 0.3695) / density (slider 2));

...

**Comment by jmskurtz** [comment]
Luke may have written these in his notebook but I can't find any other record of the equation.

**Comment by mostaphaRoudsari** [comment]
He already emailed me that he doesn't have them. I think I just write them down from the file. Hopefully tomorrow night.

**Comment by mostaphaRoudsari** [comment]
Forest Area Needed = population \* change in energy demand(slider 3) \* energy demand per person (= 131499493042) \* ((energy mix PV (slider 4) / PV per acre (= 27000000000) ) + (energy mix BioMass (slider 5)/   BioMass/Acre(= 1272633399))) :deciduous_tree:

**Comment by mostaphaRoudsari** [comment]
Wind Area Needed = population \* change in energy demand(slider 3) \* energy demand per person (= 131499493042) \* energy mix Wind (slider 6) / Wind per acre (= 2.2659e+11) :dash: 

wind per acre = potential energy from wind (60178421882779700) / Area of lake Erie in County (265579)

**Comment by mostaphaRoudsari** [comment]
Wave Area Needed = population \* change in energy demand(slider 3) \* energy demand per person (= 131499493042) \* energy mix Wave (slider 7) / Wave per acre (= 2.2659e+11) :wavy_dash: 

wave per acre = potential energy from wave (24182928000000000) / Area of lake Erie in County (265579)

**Comment by mostaphaRoudsari** [comment]
## Agriculture Area needed

Sum of items below:
1. BioFuels Area = Population \* Change in average Miles (slider 15) \* Average Miles Drive Yearly (= 3114)) / (Change in vehicle efficiency (slider 18)  \* Baseline Miles per Gallon (=23.6)) \* 88565400 \* Gasoline Mix (slider 19) / bioFuelPerAcre (=27410517697)
1. Grains Area = Population \* change in food demand(slider 8) \* food demand per person (= 2949704725) \* DietGrains (slider 9) / Grains per acre (= 9106580578)
2. Vegetables Area = Population \* change in food demand(slider 8) \* food demand per person (= 2949704725) \* DietVegetable (slider 10) / Vegetables per acre (= 657850587)
3. Fruit Area = Population \* change in food demand(slider 8) \* food demand per person (= 2949704725) \* DietFruit (slider 11) / Fruit per acre (= 1037771095)
4. Dairy Area = Population \* change in food demand(slider 8) \* food demand per person (= 2949704725) \* DietDairy (slider 12) / Dairy per acre (= 14790915944)
5. Meat Area = Population \* change in food demand(slider 8) \* food demand per person (= 2949704725) \* DietMeat (slider 13) / Meat per acre (= 92555012) :meat_on_bone:

**Comment by mostaphaRoudsari** [comment]
(Water demand) Fish Area = Population \* change in food demand(slider 8) \* food demand per person (= 2949704725) \* DietFish (slider 14) / Fish per acre (= 532690414) :fishing_pole_and_fish: :

**Comment by mostaphaRoudsari** [comment]
Natural and wetland is set to 0!

**Comment by Butcherluke** [comment]
Natural and wetland being set to 0 is an interesting topic for the paper (or future one) as it shows the 'human-centric' output of the study.

**Comment by mostaphaRoudsari** [comment]
Very good point! I agree that we should mention this in the paper.

**Comment by jmskurtz** [comment]
remove waves as part of energy mix

**Comment by jmskurtz** [comment]
Make all energy mixes equal 100% with fossil fuels as default.

**Comment by jmskurtz** [comment]
Regarding updating these, I must have misunderstood you on the call because I thought the way I had outlined the equations was sufficient. I can rewrite them and simplify them... working on doing this on the "summary" tab in the same google doc. https://docs.google.com/spreadsheets/d/1Rdb9R5--uQLwx0NqsR8qKNMnNwHsenGS8H0kGxGknjI/edit?usp=sharing
- Primary Developed Land = Developed Land + Solar PV = [ (2.71 x Density change) / Scenario Population ] + [ ( 1.92E+02 x Scenario Population x Energy Consumption Change x PV Fuel Proportion) / Fuel Production Intensity]
- Forest Land = Biomass Land = (192 x Scenario Population x Energy Consumption Change x Biomass Fuel Proportion) / Fuel Production Intensity Change

Let me know if this version of the equation is better and I'll translate each of the land areas for this form. Want to make sure you have it in the form that works best for coding!
