### ISSUE TITLE
add a table for population

### ISSUE THREAD

**Issue by mostaphaRoudsari** [mostaphaRoudsari/EmergeSettlement#5]
So we can keep track of current vs proposed scenarios

**Comment by mostaphaRoudsari** [comment]
The table is there but not connected to other graphs yet.

**Comment by Butcherluke** [comment]
Spotted a spelling mistake in the Population Table. 'Sincalirville' should be 'Sinclairville'

**Comment by mostaphaRoudsari** [comment]
Thanks for reporting! It's fixed now...
